services:
  game_server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      game_db:
        condition: service_healthy # запуск после готовности БД
    environment:
      - GAME_DB_URL=postgres://user:password@game_db:5432/db_game
    command: >
      --config-file /app/data/config.json
      --www-root /app/static
      --tick-period 10
      --randomize-spawn-points
  game_db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db_game
    #ports:
    #  - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db_game"]
      interval: 10s
      timeout: 5s
      retries: 5
  